### ISSUE TITLE
DJI menu disappears after installing the MSP-OSD 

### ISSUE THREAD

**Issue by zvikaf** [fpv-wtf/wtfos#101]
DJI V2, all goes ok, after installing the MSP-OSD package the main DJI menu disappears. 
seems that the installation is using other location / slot.
tried doing "unrd slot_1.status_successful 0, unrd slot_1.status_active 0, unrd slot_2.status_active 1" and reboot,  
got corrupted slot with no difference. 
uninstalling and reinstalling again, same result.

**Comment by bri3d** [comment]
What goggles firmware version are you using?

**Comment by zvikaf** [comment]
version is : 01.00.0600

**Comment by bri3d** [comment]
That's why. You need .0606 or later; the ordering of display layers changed since early versions and things won't work right with them.

**Comment by zvikaf** [comment]
wow... thanks, how do i upgrade without blocking ?

**Comment by bri3d** [comment]
Now that you have root it will stick. Upgrade using DJI Assistant or Butter Superpack, and re-install WTFOS.

**Comment by zvikaf** [comment]
Thanks a lot... will do 🥇

**Comment by zvikaf** [comment]
Works... thanks again :-)
