### ISSUE TITLE
Using goggles as a display for RC2 remote?

### ISSUE THREAD

**Issue by sebastienvg** [fpv-wtf/wtfos#104]
So I just got a Mini 4 Pro and I was thinking how cool it would be to use my trusty goggles instead of the display on the remote. I heard the remote support video out on the usb-c port and I was wondering if I could use the goggles as a display?

**Comment by j005u** [comment]
As explained on Discord as well, the goggles don't work with generic USB-C video in (which is just displayport). 

This would be possible if one were to modify the Fly app to forward the h264 stream via our moonlight video in protocol and as such wouldn't actually require any further development on the wtfos side.

Closing.
