### ISSUE TITLE
Goggles are not found

### ISSUE THREAD

**Issue by mixeRPL** [fpv-wtf/wtfos#12]
Hello, 

my goggles are not on the list when trying to connect to configurator but they are when attempting to root. I've done the root thing but still can not connect goggles to configurator because it is not on the list of devices. What am i doing wrong?

**Comment by j005u** [comment]
Hey there,

In case you weren't able to solve the issue already, there is now a fixed version of the configurator on https://testing.fpv.wtf/.

Closing this issue, please re-open it if you're still having problems.
