### ISSUE TITLE
Reboot on installing wtfos

### ISSUE THREAD

**Issue by Ben-Stevenss** [fpv-wtf/wtfos#13]
After rooting a airunit, it keeps rebooting when trying to install wtfos. 
First time rooting failed, after removing the sd card that was in it it worked. 
Now it just reboots on installing wtfos, and keeps looping. 

Rooting again doesn’t help
Reflashing in dji assistant not possible. 

is there any way to hard reset of force installation?

**Comment by dacan2810** [comment]
I Have same problem with caddx vista
https://github.com/fpv-wtf/wtfos-configurator/issues/93

**Comment by j005u** [comment]
This is a known issue: https://github.com/fpv-wtf/wtfos-configurator/issues/87

Closing the dupe.
