### ISSUE TITLE
OSD Layout messed up if goggles are rebooted

### ISSUE THREAD

**Issue by tonyyng** [fpv-wtf/wtfos#19]
After the initial connection, where the OSD elements are in their correct location, I disconnected my goggles battery to test the behavior with a battery swap.

After the connection between the goggles and the air unit is re-established, the OSD is unusable.  There are some random digits scattered around the screen.  If turn the power to the air unit OFF/ON, the OSD starts working again.  I have the air unit on a switch, so I'm not rebooting the FC.  

I'm using WTFOS with iNav 4.1

Thanks

**Comment by tonyyng** [comment]
![image](https://user-images.githubusercontent.com/5619549/191995771-6eb3878c-1394-4f4b-aa4d-42f30cdd7adc.png)
Using a channel to turn the OSD off and back on fixes the OSD display.

**Comment by mavenius** [comment]
Awesome workaround; thanks!
