### ISSUE TITLE
Garbled OSD Elements

### ISSUE THREAD

**Issue by umdpru** [fpv-wtf/wtfos#20]
I have experienced an issue with a caddx vista, goggles v1 that are rooted, rubbing inav 5.1 where th osd elements are garbled and mixed up on screen if the air raft unit is powered before the goggles. It does this reliably. If th bgoggles are powered first then it is fine. 
![20220925_085942](https://user-images.githubusercontent.com/6453570/192161604-320e6961-fd0a-4dab-b233-8056b28abc83.jpg)

**Comment by bri3d** [comment]
This is expected at this time, especially if you are using HD mode. The INAV HDZero HD OSD code never sends a "sync" / full screen update message after the first time it connects to the VTx, so if the goggles aren't around to see the very first messages from the FC, it won't work properly.

I am working on a fix for this on the INAV side.
