### ISSUE TITLE
can't find the caddx vista(dji air unit lite) when root device

### ISSUE THREAD

**Issue by Luukk1919** [fpv-wtf/wtfos#24]
I had root my DJI goggles V1 and all are okay.
when I want to root my caddx vista it is not shown on the pop list box.
but my computer can recognize that and it's shown in the DJI assistant app also.
my computer is 2019 macbook pro and it's still not shown when I try to root on a win 10 labtop.
P.S.  I use google  chrome app and all are the least version.

I had spent two nights to try to solve it and can't figure out how to do.
I installed the CDC serial driver and the bulk interface driver on my computer and it doesn't work.
please help me. 
thanks so much.

Luke

**Comment by EVilm1** [comment]
Hi, You can try to reboot, do not open DJI Assistant to avoid occupying the serial port.
If this does not work, make sure you have a usb C cable with data transfer.

**Comment by unrealkingdom** [comment]
I have same problem..with other USB i was try,but with other vista lite it'oke..air unit lite firmware 0608 with runcam wasp,
this is message i found "Could not connect to device, make sure that adb server is not running on your machine (adb kill-server) and that you are not connected in another tab/window." anybody can help me?

**Comment by j005u** [comment]
The configurator has since been significantly improved and you should no longer run into these issues.

If you do then please open a new issue including your trace-id from the bottom left of the page.
