### ISSUE TITLE
Air unit stuck in a connected/disconnected loop (no video)

### ISSUE THREAD

**Issue by Spit29** [fpv-wtf/wtfos#27]
I can't seem to get my dji air unit to work after rooting and installing WTFOS.. I don't get video and it seems to just boot loop. I am getting a repeating on and off usb connection. I'm not able to connect to the air unit via usb though.. Any help is greatly appreciated.
I was able to root it and install the OSD mod but now it just loops...

**Comment by LouDnl** [comment]
How are you powering the AU?

**Comment by j005u** [comment]
Try booting while holding down the bind button. It should start in safe mode and allow you to re-connect in assistant.

**Comment by Spit29** [comment]
> 

Powered by a new speedybee F7 v3 + 6s battery. It worked before the Wtfos. Holding the bind button while powering doesn't seem to do anything. Led us solid red

**Comment by Spit29** [comment]
Got it! Tried it on another drone and it worked. Turned out the wiring is not correct when using the plugs the Speedybee f7 v3 came with.. Very annoying..
