### ISSUE TITLE
Alpha but how much alpha?

### ISSUE THREAD

**Issue by DimitarKrastev** [fpv-wtf/wtfos#3]
Hey, I want to give it a try. You mentioned it is "very alpha" and of course everything I am doing is my own risk, but I want to know what kind of risk we are talking about.

If I use margerine payload and install the msp osd from bri3d should I look for something that can go wrong? For instance you mentioned in an issue that crashdumps could fill up the space. Is this catastrophic if it happens? Is it reversable with the bind button during startup?

Should I do something to have the bind button safety enabled or is it there by default?

Thanks, cant wait to give it a try.

**Comment by j005u** [comment]
The crashdump issue _should_ be fixable by holding down the bind button, yes. In that specific situation, it should result in wtfos getting wiped and disabled during startup permanently and the filled partition would be freed.

Bind button safety is enabled by default.

In general, most things released to the wtfos repository should be in a state that don't brick your system permanently and should be fixable by holding down the bind button and reinstalling wtfos or in the worst case some further debugging.

With that said, it definitely is possible for a critically buggy or malicious package to cause permanent damage.

The applications and mods themselves in their current state might definitely have bugs, crashes and unexpected interactions across packages.
