### ISSUE TITLE
Goggles V1 and Air unit don't show the OSD after installing WTFOS stuff, dont show quad battery status and DJI assistant 2 show error: Cannot load firmware list (4-10)

### ISSUE THREAD

**Issue by ObiVanDunobi** [fpv-wtf/wtfos#30]
Hi,
today I tried to unlock the full betaflight OSD through WTFOS.
Root process, also installing WTFOS and packages (FCC and msp_osd) done, CLI and other Betaflight was set according to JB video.
But alfter all of that, OSD in goggles not showing up, quad battery voltage is gone and when I trying to open firmware list at DJI Assistant 2 it shows error with code:
Cannot load firmware list. (4-10)
This error show for both devices - goggles and air unit.
Custom OSD is ON in goggles
In goggles I just see at the right bootom corner: OSD WAITING...
I can change every setting via goggles so I think the vista works.
What can I do for showing battery voltage at least please?
Before applying WTFOS I got batt and also GPS values (Home point direction, distance and GPS position of quad).
Now they just disapear.
Dump file attached
Thank you

[BTFL_cli_Nazgul5_V2_20221014_224333.txt](https://github.com/fpv-wtf/wtfos/files/9789989/BTFL_cli_Nazgul5_V2_20221014_224333.txt)

**Comment by ObiVanDunobi** [comment]
SOLVED
Dumb user  :/
In CLI comands I didnt write SAVE so the CLI never saved up MSP settings.
But DJI assistant still didnt wok. I can live with that if I will never need DJI assistant 2 any more. Hope I will never need it again :D
Sorry for false issue.
Thak you
Juraj

**Comment by magizusebas** [comment]
Hello, i am having the exact same problem, but after saving the cli for MSP, i still cant see the betaflight osd, i dont know if you could help me or if you were able to find a way to connect to dji assistant 2

**Comment by ObiVanDunobi** [comment]
> Hello, i am having the exact same problem, but after saving the cli for MSP, i still cant see the betaflight osd, i dont know if you could help me or if you were able to find a way to connect to dji assistant 2

Hi, make sure that you have all betaflight settings according to JB or Oscar Liang and your MSP port should be -1 from your actual UART where you have air unit soldered.
My OSD works well now. 
I think you have to turn off Custom OSD in DJI Goggles.
For dji assistant, I dont use it any more.
Still not able to change firmware because of error message (Cannot load firmware list).
But there is a way how to able it again.
If you have installed WTFOS, you have to run one phrase at CLI.
See this from 5:30.
https://www.youtube.com/watch?v=vubarw7BJkw
Good luck and let me know 😉

**Comment by Chupokabra5** [comment]
The same thing doesn’t work at all I’ve tried the cli and the preset and 4.4

**Comment by Chupokabra5** [comment]
Betaflight 4.4*

**Comment by ObiVanDunobi** [comment]
Hi,

I dont remember how I made it but its work for me now.
I know I made a one mistake:
I didnt hit the Save button after putting commands in CLI.
So try to do all the steps again and dont forget save CLI commands.
Let me know if it helps.

Dňa so 4. 11. 2023, 9:06 Chupokabra5 ***@***.***> napísal(a):
