### ISSUE TITLE
How to enable live-audio on DJI FPV Goggles V1

### ISSUE THREAD

**Issue by ez4fm** [fpv-wtf/wtfos#33]
I have installed this package, but I don't know how to enable it

**Comment by j005u** [comment]
It should just work, if you have a full size air unit on the other end.

It can't work with Vistas, as they don't have a microphone.

**Comment by ez4fm** [comment]
Thank you.
I'm using RunCam Link Wasp now, I'll try it on DJI air unit again.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Joonas ***@***.***>
发送时间: 2022年10月31日 18:54
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [fpv-wtf/wtfos] How to enable live-audio on DJI FPV Goggles V1 (Issue #33)


It should just work, if you have a full size air unit on the other end.

It can't work with Vistas, as they don't have a microphone.

―

**Comment by gmoska** [comment]
Could someone share the pinage of the audio? I tried live-audio without sucess :(

**Comment by j005u** [comment]
Pinage? You just need to plug in headphones, install the package on your goggles V1 and use a full size Air Unit.

@gmoska if you have a problem, please open another issue with a detailed description of what you did, what devices were involved and what happened.

Closing this issue as the original problem seems to have been using a vista.
