### ISSUE TITLE
Updated to 01.02.0015 not able to root

### ISSUE THREAD

**Issue by joe-0310** [fpv-wtf/wtfos#34]
Hello,

I am not able to install wtfos because I updated to 01.02.0015, are you working on a hack to root from this version or is this to be considered hopeless?

**Comment by ako82** [comment]
Stay tuned. There is something in the cooking.
Don't upgrade any further.


...or some similar reply would be more than enough to this question. I would also like to know if there is some hope in the horizon :(

**Comment by j005u** [comment]
Feel free to upgrade past 0015, it doesn't make a difference.

We've stated in several places that we are in fact working on a solution, but it's going to take some undetermined amount of time to get to anything publicly releasable.

No updates means we're still working on it.

**Comment by ako82** [comment]
Ahhh... that's something! Thanks for all your efforts, take all the time you need!
