### ISSUE TITLE
How to change OSD font?

### ISSUE THREAD

**Issue by Anton33455** [fpv-wtf/wtfos#35]
Any idea how to change the fonts?  Font stays the same in goggles regardless what I choose in BF

**Comment by EVilm1** [comment]
Hi, you can check this video around 11:30 : https://www.youtube.com/watch?v=hNOA0kUjKhY
this will answer your question ;)

**Comment by Anton33455** [comment]
So no fonts as of now.. Funny that I like MaddsTech font.  Mine looks like
retro.  How did he get that font?

**Comment by j005u** [comment]
Fonts are currently handled by placing the correct file on your SD card. BF font selection is not honored.

There's a few fonts linked in the msp-osd README and instructions here: https://github.com/fpv-wtf/msp-osd#suggested-third-party-fonts
There's also SneakFPVs font at: https://drive.google.com/drive/folders/1buxrXqhU46AxE3fwaFDsMb97IiGLVa95

A future update will bring font installation into the configurator.

**Comment by cmanley** [comment]
Are there previews of the fonts somewhere?
