### ISSUE TITLE
Using inav and betaflight running in 1 googles

### ISSUE THREAD

**Issue by erlandlieFPV** [fpv-wtf/wtfos#43]
hi, im using betaflight for my fpv quadcopter, 3 of them working great,
but i have one question....
i see the font for the inav and betaflight its different,? right/

so, can i running betaflight font (which already insert it into googles mmc)
in case use it with INAV too?
or i have to replace the font in the google, everytime i change my betaflight quadcopter to my inav fixed wing?

thanks before

**Comment by j005u** [comment]
You can have fonts per FC type on the SD Card, please see here: https://github.com/fpv-wtf/msp-osd#fc-specific-font-file-names
