### ISSUE TITLE
Feature request: Allow FPV Controller 2

### ISSUE THREAD

**Issue by axelfran** [fpv-wtf/wtfos#50]
With the newest firmware DJI has enabled the FPV Controller 2 for use with the Caddx Vista etc., but then you can not use the Googles v2. 

Would it be within the scope of this project to enable support for the Googles v2 with the FPV Controller 2 on the Vista?

Would be awesome!

**Comment by j005u** [comment]
I'm afraid due to RC related code being deep inside the binary RF RTOS it's exceedingly difficult for us to modify it at all, let alone add support for a whole new device.

So in short while not technically against the laws of physics, it's pretty definitely out of scope for us.
