### ISSUE TITLE
Cannot update through Assistant my rooted units

### ISSUE THREAD

**Issue by Kamdozer** [fpv-wtf/wtfos#53]
Today i tried to update my rooted units and vistas to make them compatible with Goggles 2. Unfortunately with no success. Both type unit and vista were recognized by DJ assistant (both consumer an FPV versions), but no firmware was listed. Only error to obtain firmware 4-10 error. I tried a lot of things. In the end I decided to update an unrooted vista and voila - no issues. I am on mac. So obviously DJI has locked in some way updates for rooted devices. I guess my only option is to remove the root, but could not find info how to do it on the units. My goggles v.2 will remain rooted for other reasons, but I move to goggles 2 and now i can not update my rooted hardware for the purpuse. Any suggestions guys?
![C5CC8E5F-7E82-422A-AAE5-ACCE46B5D132](https://user-images.githubusercontent.com/43016159/212084900-60a0d1ae-5d52-43ea-b6ff-414006bbf839.jpeg)

**Comment by xviews** [comment]
1. remove WTFOS
2. CLI wtfos-remove-adb

**Comment by Kamdozer** [comment]
Thanks a bunch. It worked!

**Comment by tiac0o** [comment]
> 1. remove WTFOS
> 2. CLI wtfos-remove-adb

I did the step 1 and success, but when i exec the CLI command, it says can`t find the 'wtfos-remove-adb' command
