### ISSUE TITLE
Map OSD Not Loading into Googles V2 (.bin messages)

### ISSUE THREAD

**Issue by RussellPinks** [fpv-wtf/wtfos#55]
1. My Goggles V2 and DJI Air Unit are on DJI Firmware V01.00.0606

2. I've rooted my Goggles V2, installed wtfos and installed map osd (I have triple-checked that it's rooted, installed and map osd installed)

3. I have rooted my DJI Air Unit, installed wtfos and installed map osd (Again I've triple-checked and it's all definitely on there!) 

4. I have connected my FC, checked my ports and MSP is on 'UART2', then went to SLI and typed:
set osd_displayport_device = MSP
set displayport_msp_serial = 1

5. I have made sure that my OSD settings in Betaflight are all configured correctly by setting the video format to 'PAL' and hit save. (If a disconnect my FC and reconnect all the settings have saved fine)

6. When booting up my quad and Goggles V2, the map osd isn't loading but I do get some strange .bin messages on the Goggles - I have attached a video of the issue.

I have connected my FC, checked my ports and MSP is on 'UART2', then went to SLI and typed::
set osd_displayport_device = MSP
set displayport_msp_serial = 1

It's worth mentioning that my FC firmware is on BF 4.3.2
Betaflight configurator is firmware 10.8.0

Any ideas on what I can do to get past this issue?!

https://user-images.githubusercontent.com/122650218/212470054-f0a4e65a-1de0-4bdc-a0a6-eff42e0e5cfd.MOV

**Comment by j005u** [comment]
From your description I can't tell what might be wrong.

The messages you get at startup are normal and indicate that msp-osd is working fine on the Goggles side.

It will be easier to troubleshoot if you join the #osd-support channel on our Discord: https://discord.gg/3rpnBBJKtU

I'll close this ticket for now, if need be please re-open on the msp-osd repo here: https://github.com/fpv-wtf/msp-osd
