### ISSUE TITLE
OSD issue

### ISSUE THREAD

**Issue by KennyFPV** [fpv-wtf/wtfos#56]
Hi
In two of my drone I have an issue with the OSD (in all other drone the OSD work propertly)
If I enable the telemetry option in the receiver tab of betaflight the RSSI, RSSI db and Link Quality value start blinking and randomly goes to 0 (all other value in the osd work fine)
If I desable the telemetry option all value are perfect (also RSSI, RSSI db and Link Quality)
I have the same issue On all version of betaflight (4.2.x or 4.3.x or 4.4)
Anyone can help me to solve it?

**Comment by j005u** [comment]
This seems like a BF issue rather than wtfos or msp-osd issue at least at first glance.

You might have better luck getting help with it on our Discord: https://discord.gg/3rpnBBJKtU

Closing for now, but if it turns out to be wtfos related after all, please do re-open.
