### ISSUE TITLE
OSD Scaling Glitch

### ISSUE THREAD

**Issue by hickscorp** [fpv-wtf/wtfos#57]
I'm using a Caddx Vista and a Googles v2.
I tried all options for MSP OSD in BF `4.4 RC4` and `4.4 RC5` (In particular `Auto` and `HD`).
Here's what I observed so far.

- If Googles are powered first and left to boot for a moment, then powering on the quad seems fine. The OSD elements are scaled to HD and use all the 16:9 space available.
- If I power the quad first, or if the googles havn't finished booting, then I get the low definition version, where texts are huge and can't be placed on the left and right black bands - they're centered in the 4:3 part of the picture.
- If I power on the quad first, googles then, the problem happens. At this point if I power-cycle the quad the problem remains - although the googles are now available when the quad powers on.

**Comment by Alveran81** [comment]
I can confirm that, I have the same problem.

**Comment by CrashOftenFPV** [comment]
Yeah I've got the same issue on two quads.

**Comment by j005u** [comment]
Tagging @bri3d so he can review the issue.

For future reference, please report msp-osd issues at: https://github.com/fpv-wtf/msp-osd

**Comment by hickscorp** [comment]
Thanks @j005u . Should I move the issue?

**Comment by hickscorp** [comment]
I am referencing the issue in the `fpv-wtf/msp-osd` tracker and closing this one. Apologies for posting in the wrong place!
