### ISSUE TITLE
DJI Goggles V2 Version Question

### ISSUE THREAD

**Issue by Alveran81** [fpv-wtf/wtfos#58]
Hello,

i have rootet my DJI Goggles V2 and installed WTFOS. Everything works fine. HD OSD with Caddx Vista and Betaflight 4.4 is very nice.
I also own DJI FPV Drone. **What is the highest Version I can Install on Goggles in DJI FPV Drone Mode?** In future i will buy DJI AVATA or DJI O3 Air Unit.

**Comment by j005u** [comment]
So far you can install the latest version (01.06.0000 as of writing) and then re-install wtfos without any known issues.
