### ISSUE TITLE
WTF.OS not working on 1.05 and +

### ISSUE THREAD

**Issue by illest90s** [fpv-wtf/wtfos#60]
I had my goggles on 1.05 before rooting so i downgraded with wtf butter. After that i rooted and then upgraded to 1.06 the latest fw from the dji assistant 2, so i could use dji o3 air unit. Connected to the WTFOS Configurator that then tells me the os is installed on the wrong slot, so on slot 2. I let it fix that and after reboot no more dji o3 support.

help

**Comment by seccafico8** [comment]
Having a similar issue. When WTF OS is installed on 1.05 or 1.06 you lose all the new o3 settings such as 30fps mode, sharpening and noise control.
