### ISSUE TITLE
Long Range software limit

### ISSUE THREAD

**Issue by a-di-ez** [fpv-wtf/wtfos#66]
Is it possible to remove the software limitation of 13km for flying wings?

**Comment by edernucci** [comment]
As stated on https://discord.com/channels/849931046883819550/1023730599711748139/1023730794121932901
> Is there a way to get past the 13.3KM limit? 
No, and unlikely to happen

**Comment by a-di-ez** [comment]
> As stated on https://discord.com/channels/849931046883819550/1023730599711748139/1023730794121932901
> > Is there a way to get past the 13.3KM limit? 
> No, and unlikely to happen

Not found
