### ISSUE TITLE
Could not connect to device, make sure that adb server is not running on your machine (adb kill-server) and that you are not connected in another tab/window.

### ISSUE THREAD

**Issue by levin-wy** [fpv-wtf/wtfos#68]
When I connet the DJI  Air Unit,it show me this:
Could not connect to device, make sure that adb server is not running on your machine (adb kill-server) and that you are not connected in another tab/window.

**Comment by vjvenida** [comment]
I have the same error..  Are you able to fix this error? thanks

**Comment by levin-wy** [comment]
> 

I haven't found a way.

**Comment by vjvenida** [comment]
I'm trying this fix right now. I think you should too.. 

https://github.com/fpv-wtf/wtfos-configurator/issues/230

**Comment by vjvenida** [comment]
dude, fixed mine.. its now working.
Run butter, update dji assistant 0606 then re-root goggle then install wtfos.
https://github.com/fpv-wtf/margerine/wiki/Troubleshooting#wtfos-install-stuck-in-a-loop

**Comment by vjvenida** [comment]
WTFOS Team, Thank you so much for this!

**Comment by yak-54** [comment]
Hi i have this issue as well with an air unit 
i did update v1 googles is fine i did one air unit as well its fine 
went to do one more air unit and all i get is this 

Could not connect to device, make sure that adb server is not running on your machine (adb kill-server) and that you are not connected in another tab/window

**Comment by suprchunk** [comment]
> 

Same here. Worked last week, on the same unit.

**Comment by j005u** [comment]
This issue should be fixed by going to https://fpv.wtf/root and re-rooting. Sometimes you may have to do it multiple times during an install process.

Tracking this as a recursion here: https://github.com/fpv-wtf/wtfos-configurator/issues/176
