### ISSUE TITLE
Screensaver error

### ISSUE THREAD

**Issue by Sly501** [fpv-wtf/wtfos#70]
Screen saver not working.
I set it based on the description below:
https://github.com/D3VL/wtfos-image-configurator

Spalshscreen appears but the screensaver never starts.
It only works when I remove the MSP-OSD package.
Someone has a screen saver working?

Thanx,

**Comment by D3VL-Jack** [comment]
This is due to how MSP-OSD works, it uses the same rendering layer that the screensaver uses, effectively blocking it from working. 
At this time, it's a wontfix.

- Jack
