### ISSUE TITLE
Continue record after change battery

### ISSUE THREAD

**Issue by dangerousvasil** [fpv-wtf/wtfos#73]
## My case 
i have mini quad 3min fly time

#### my steps
1. insert battery
2. goggles v2 start record  (auto-record plugin start recording automatically as soon as an air unit is connected)
3. flying -> landing 
4. disconnect battery 
5. goggles v2 stop recording
6. Profit!
7. connect new battery 
8. goggles v2 NOT start recording
3. flying then landing 
4. disconnect 
5. NO Profit!

#### what i expect 
2 separate files for each flight
from connect battery to disconnect battery!

#### what i get 
only one file for first flight......

**Comment by j005u** [comment]
We need to do a better job at documenting the various repos, but improvement requests for auto-record should be filed under the auto-record repo issues: https://github.com/LouDnl/wtfos-auto-record/issues
