### ISSUE TITLE
Feature request: HDMI in with USB-C 

### ISSUE THREAD

**Issue by Dunsteer** [fpv-wtf/wtfos#92]
Hi, is it possible with software to enable HDMI in on goggles V2 with the USB-C to HDMI cable?

**Comment by j005u** [comment]
It is not possible, the required hardware is not present on the P1 chip.

It is theoretically possible to use a usb-c HDMI capture card, but would require a lot of development and would add latency overhead.

Please see here for what is currently possible (using h264 over USB): https://github.com/fpv-wtf/dji-moonlight-embedded
