### ISSUE TITLE
goggles v2 update crash

### ISSUE THREAD

**Issue by mb74700** [fpv-wtf/wtfos#98]
Hello, 
I tried to update my goggles. it crashes. black screen and usb permanently connected and disconnected, 
not possible to connect to computer. 
have you ever had this happen? 

THANKS

**Comment by j005u** [comment]
Could you please offer a few more details: were you updating the DJI firmware? If so to what version? Or wtfos?

In any case, you should be able to recover using butter if the firmware got corrupted: https://github.com/fpv-wtf/butter

**Comment by mb74700** [comment]
Hello, thank you for your quick response.
in downgrade with wtfo crash.
usb reboot can't flash with it
thanks
sorry for my English
________________________________
De : Joonas Trussmann ***@***.***>
Envoyé : lundi 27 novembre 2023 11:06
À : fpv-wtf/wtfos ***@***.***>
Cc : mb74700 ***@***.***>; Author ***@***.***>
Objet : Re: [fpv-wtf/wtfos] goggles v2 update crash (Issue #98)


Could you please offer a few more details: were you updating the DJI firmware? If so to what version? Or wtfos?

In any case, you should be able to recover using butter if the firmware got corrupted: https://github.com/fpv-wtf/butter

**Comment by j005u** [comment]
So it crashed while downgrading with butter?

**Comment by mb74700** [comment]
yes
________________________________
De : Joonas Trussmann ***@***.***>
Envoyé : lundi 27 novembre 2023 11:18
À : fpv-wtf/wtfos ***@***.***>
Cc : mb74700 ***@***.***>; Author ***@***.***>
Objet : Re: [fpv-wtf/wtfos] goggles v2 update crash (Issue #98)


So it crashed while downgrading with butter?

**Comment by j005u** [comment]
And now the goggles are in a permanent disconnect-reconnect reboot loop? Both without butter and when trying to use butter?

**Comment by mb74700** [comment]
yes permanent disconnect-reconnect and screen stays black.
________________________________
De : Joonas Trussmann ***@***.***>
Envoyé : lundi 27 novembre 2023 12:01
À : fpv-wtf/wtfos ***@***.***>
Cc : mb74700 ***@***.***>; Author ***@***.***>
Objet : Re: [fpv-wtf/wtfos] goggles v2 update crash (Issue #98)


And now the goggles are in a permanent disconnect-reconnect reboot loop? Both without butter and when trying to use butter?

**Comment by j005u** [comment]
I have not seen butter kill any goggles so far, this is quite strange.

Is your battery properly charged and the power cable is making good contact?

**Comment by mb74700** [comment]
yes try with 3 batteries and 3 cables
________________________________
De : Joonas Trussmann ***@***.***>
Envoyé : lundi 27 novembre 2023 12:14
À : fpv-wtf/wtfos ***@***.***>
Cc : mb74700 ***@***.***>; Author ***@***.***>
Objet : Re: [fpv-wtf/wtfos] goggles v2 update crash (Issue #98)


I have not seen butter kill any goggles so far, this is quite strange.

Is your battery properly charged and the power cable is making good contact?

**Comment by j005u** [comment]
Which butter .zip file did you use exactly?
Are these second hand goggles? If so, is there printing that says "FPV Goggles V2" on the underside of the nose part of the goggles?

**Comment by mb74700** [comment]
I used the butter from gl150_01.00.0606_recovery.
used glasses.
I have the QRcode
________________________________
De : Joonas Trussmann ***@***.***>
Envoyé : lundi 27 novembre 2023 12:23
À : fpv-wtf/wtfos ***@***.***>
Cc : mb74700 ***@***.***>; Author ***@***.***>
Objet : Re: [fpv-wtf/wtfos] goggles v2 update crash (Issue #98)


Which butter .zip file did you use exactly?
Are these second hand goggles? If so, is there printing that says "FPV Goggles V2" on the underside of the nose part of the goggles?

**Comment by j005u** [comment]
There's your problem, that package is for V1 goggles.

Use this instead: https://bin.fpv.tools/butter/packages/gl170_01.07.0000_superpack.zip

**Comment by mb74700** [comment]
Thank you very much,
I restarted with gl170_01.07.0000_superpack and I managed to reboot
________________________________
De : Joonas Trussmann ***@***.***>
Envoyé : lundi 27 novembre 2023 12:56
À : fpv-wtf/wtfos ***@***.***>
Cc : mb74700 ***@***.***>; Author ***@***.***>
Objet : Re: [fpv-wtf/wtfos] goggles v2 update crash (Issue #98)


There's your problem, that package is for V1 goggles.

Use this instead: https://bin.fpv.tools/butter/packages/gl170_01.07.0000_superpack.zip
